local M = {}

M.icons = {
	ui = {
		icons = {
			branch = "",
			bullet = "•",
			open_bullet = "○",
			ok = "✔",
			d_chev = "∨",
			ellipses = "…",
			node = "╼",
			document = "≡",
			lock = "",
			r_chev = ">",
			warning = " ",
			error = " ",
			info = "󰌶 ",
		},
		kind_icons = {
			Array = " 󰅪 ",
			BlockMappingPair = " 󰅩 ",
			Boolean = "  ",
			BreakStatement = " 󰙧 ",
			Call = " 󰃷 ",
			CaseStatement = " 󰨚 ",
			Class = "  ",
			Color = "  ",
			Constant = "  ",
			Constructor = " 󰆧 ",
			ContinueStatement = "  ",
			Copilot = "  ",
			Declaration = " 󰙠 ",
			Delete = " 󰩺 ",
			DoStatement = " 󰑖 ",
			Element = " 󰅩 ",
			Enum = "  ",
			EnumMember = "  ",
			Event = "  ",
			Field = "  ",
			File = "  ",
			Folder = "  ",
			ForStatement = "󰑖 ",
			Function = " 󰆧 ",
			GotoStatement = " 󰁔 ",
			Identifier = " 󰀫 ",
			IfStatement = " 󰇉 ",
			Interface = "  ",
			Keyword = "  ",
			List = " 󰅪 ",
			Log = " 󰦪 ",
			Lsp = "  ",
			Macro = " 󰁌 ",
			MarkdownH1 = " 󰉫 ",
			MarkdownH2 = " 󰉬 ",
			MarkdownH3 = " 󰉭 ",
			MarkdownH4 = " 󰉮 ",
			MarkdownH5 = " 󰉯 ",
			MarkdownH6 = " 󰉰 ",
			Method = " 󰆧 ",
			Module = " 󰅩 ",
			Namespace = " 󰅩 ",
			Null = " 󰢤 ",
			Number = " 󰎠 ",
			Object = " 󰅩 ",
			Operator = "  ",
			Package = " 󰆧 ",
			Pair = " 󰅪 ",
			Property = "  ",
			Reference = "  ",
			Regex = "  ",
			Repeat = " 󰑖 ",
			Return = " 󰌑 ",
			RuleSet = " 󰅩 ",
			Scope = " 󰅩 ",
			Section = " 󰅩 ",
			Snippet = "  ",
			Specifier = " 󰦪 ",
			Statement = " 󰅩 ",
			String = "  ",
			Struct = "  ",
			SwitchStatement = " 󰨙 ",
			Table = " 󰅩 ",
			Terminal = "  ",
			Text = " 󰀬 ",
			Type = "  ",
			TypeParameter = "  ",
			Unit = "  ",
			Value = "  ",
			Variable = "  ",
			WhileStatement = " 󰑖 ",
		},
	},
	nonprog_modes = {
		["markdown"] = true,
		["org"] = true,
		["orgagenda"] = true,
		["text"] = true,
	},
}

local icons_spaced = {}
for key, value in pairs(M.icons.ui.kind_icons) do
	icons_spaced[key] = value .. ""
end

M.icons.ui.kind_icons_spaced = icons_spaced

return M
